#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。
name: HackerFollower
# 描述/签名
description:  To follow the path:<br> look to the master,<br> follow the master,<br> walk with the master,<br> see through the master,<br> become the master.

#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png

# 菜单中的按钮
navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  behance: # https://www.behance.net/<>
  douban: hackerfollower # https://www.douban.com/people/<>
  dribbble: # https://dribbble.com/<>
  email: hackerfollower@163.com 
  facebook: hackerfollower #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: hackerfollower #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  medium: #https://medium.com/<>
  pinterest: #https://www.pinterest.com/<>
  reddit: #https://www.reddit.com/user/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: hackerfollower # https://www.twitter.com/<>
  weibo: liubuhu #https://www.weibo.com/<>
  youtube: # channel/<> or user/<>
  zhihu: hackerfollower #https://www.zhihu.com/people/<>

# 站点页脚的文字
footer-text: Copyright (c) 2019 LiuLang

# 评论，注意，请不要同时添加多种不同的评论区

# 输入Disqus shortname，即可添加评论区
disqus: #shortname

# 输入Gitalk相关设定，即可添加评论区
gitalk:
  clientID: f1c2299e9523be45ea9d
  clientSecret: 657eda5920f06ec00fe4069d89d98061f6a02a16
  repo: hackerfollower.github.io
  owner: hackerfollower

# 输入Google Analytics web tracking code
google_analytics: UA-155037305-1

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: "https://hackerfollower.org"

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: ""

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:year/:month/:day/:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

